name: HACS Action

# Runs only when triggered manually from the Actions tab.
on:
  workflow_dispatch:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
